name: Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: Upload project via FTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          server-dir: /
          exclude: |
            **/.git*
            **/.github*
            **/README.md
